version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: toms223
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - ../PostgreSQL:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: