apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: pe
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Users" (
      "Id" SERIAL PRIMARY KEY,
      "Name" VARCHAR(255),
      "Email" VARCHAR(255),
      "HashedPassword" VARCHAR(255)
    );
    CREATE TABLE IF NOT EXISTS "Expenses" (
      "Id" SERIAL PRIMARY KEY,
      "Name" VARCHAR(255),
      "Amount" REAL NOT NULL,
      "Date" DATE NOT NULL,
      "UserId" INT,
      "Continuous" BOOLEAN,
      "Period" INT,
      "Fixed" BOOLEAN,
      FOREIGN KEY ("UserId") REFERENCES "Users"("Id")
    );
