version: '3.8'

services:
  personalexpenses:
    build:
      context: ..
      dockerfile: ./Deployment/Docker/Dockerfile
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${MICROSOFT_CLIENT_SECRET}
    ports:
      - "80:8080"
    networks:
      - server
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ../PostgreSQL:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - server

volumes:
  postgres_data:
    
networks:
  server:
    driver: bridge